### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Ionizing** [haidi-ustc/maptool#2]
- [ ] fix bugs , add comment, add manual
- [x] unittest
- [ ] calculation of cohp
- [ ] molecule and crystal match
- [ ] finger print of structure
- [ ] prediction of volume for structure
- [ ] EOS calculation and visualization
- [ ] Quasi-harmonic Debye approximation that used to compute thermal properties.
- [x] XRD calculation and visualization
- [x] defect structure
- [x] doping structure
- [ ] mechanical properties input preparation and output analysis
- [ ] database (local , mongodb)
- [ ] workflow (vasp)
- [x] rdf calculation
- [ ] effect mass
- [ ] carries mability
- [ ] command parsing
- [ ] pip install or Anacoda sh package install
- [ ] Vasp related
  - [ ] band dos visualization
  - [ ] wavecar visualization
  - [ ] INCAR POTCAR KPOINTS preparation
  - [ ] MD trajectory analysis
  - [ ] optical properties

**Comment by Ionizing** [comment]
I found that implementation of HSE KPOINTS generation is left empty, I will do the job.

- [x] implement HSE KPOINTS generation

**Comment by Ionizing** [comment]
- [x]  defect structure
- [x]  doping structure
- [x]  rdf calculation
- [ ] finger print of structure
- [x] prediction of volume for structure, [link](https://note.youdao.com/ynoteshare1/index.html?id=774951997f1d2dce94e204c079882c4b&type=note)
- [x] XRD calculation and visualization
- [ ]  molecule and crystal match

**Comment by Ionizing** [comment]
- [x] RDF function reference: https://github.com/materialsproject/pymatgen/blob/v2020.4.2/pymatgen/analysis/chemenv/coordination_environments/voronoi.py#L682-L740

I'm going to split the function into two, one returns the raw RDF data and the other returns the figure.

**Comment by Ionizing** [comment]
- [x] complement of RDF io & visualization
- [x] implement XRD calculation & visualization

**Comment by Ionizing** [comment]
- [ ] vasp-output
- [ ] WAVECAR -> PARCHG
- [ ] simple CLI demo
- [ ] [Hetero junction](https://note.youdao.com/ynoteshare1/index.html?id=1ca741c40944a9d653c58d13e4dbb0e5&type=note)
- [ ] Add interface to `dedup` method
- [ ] Change logic that compares energy first in `dedup` method. A list of energy would be passed in.

**Comment by Lauren-Jiao** [comment]
- [ ] vasp-input
